######################################################################
# Automatically generated by qmake (2.01a) ti lokakuuta 23 11:14:26 2012
######################################################################
include(../../common.pri)
TEMPLATE = lib
TARGET = $$qtLibraryTarget(photosplugin)
CONFIG += plugin mobility
DEPENDPATH += .
INCLUDEPATH += . ../../lib
MOBILITY += gallery

LIBS += -lgallerymediasource -L../../lib

# Input
HEADERS += photoplugin.h \
    photomodel.h
SOURCES += photoplugin.cpp \
    photomodel.cpp


# Weird stuff, but this is needed for deployment. Get rid of this!
include(../../src/qmlapplicationviewer/qmlapplicationviewer.pri)


target.path = $$DEPLOYMENT_PATH/plugins

INSTALLS += target
