######################################################################
# Automatically generated by qmake (2.01a) ti lokakuuta 23 11:14:26 2012
######################################################################
include(../../common.pri)
TEMPLATE = lib
TARGET = $$qtLibraryTarget(photosplugin)
CONFIG += plugin mobility
DEPENDPATH += .
INCLUDEPATH += . ../../lib
MOBILITY += gallery

LIBS += -lgallerymediasource -L../../lib

# Input
HEADERS += photoplugin.h \
    photomodel.h
SOURCES += photoplugin.cpp \
    photomodel.cpp


#qml.files = PhotoIcon.qml
#qml.path = $$DEPLOYMENT_PATH/plugins
target.path = $$DEPLOYMENT_PATH/plugins
INSTALLS += target #qml

OTHER_FILES += \
    PhotoIcon.qml

RESOURCES += \
    photoplugin.qrc
