######################################################################
# Automatically generated by qmake (2.01a) ke lokakuuta 24 09:58:55 2012
######################################################################

TEMPLATE = lib
TARGET = gallerymediasource
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += shared

# Input
HEADERS += mediasourceinterface.h \
    mediasourcemodelinterface.h
SOURCES += mediasourceinterface.cpp \
    mediasourcemodelinterface.cpp

target.path = /usr/lib
INSTALLS += target
